theme: jekyll-theme-minimal
title: Bochuan Lyu
description: Optimization Researcher and Developer <br> <br>
Email&#58; bochuan &#91;dot&#93; lyu &#91;at&#93; gmail &#91;dot&#93; com <br> 
<a href="https://www.linkedin.com/in/bochuan-lyu-270307121/"> &#91;LinkedIn&#93; </a>
<a href="https://scholar.google.com/citations?user=TZQALw0AAAAJ&hl=en"> &nbsp; &#91;Google Scholar&#93; </a>
logo: logo.jpg

